#pragma once

#include <mode/concepts/complex.hpp>
#include <mode/concepts/error_controller.hpp>
#include <mode/concepts/method.hpp>
#include <mode/concepts/problem.hpp>
#include <mode/concepts/root_finder.hpp>
#include <mode/concepts/scalar.hpp>
#include <mode/cuda/decorators.hpp>
#include <mode/cuda/function.hpp>
#include <mode/error/controller/integral_controller.hpp>
#include <mode/error/controller/proportional_integral_controller.hpp>
#include <mode/error/controller/proportional_integral_derivative_controller.hpp>
#include <mode/error/error_evaluation.hpp>
#include <mode/error/extended_result.hpp>
#include <mode/iterator/adaptive_step_size_iterator.hpp>
#include <mode/iterator/coupled_iterator.hpp>
#include <mode/iterator/fixed_step_size_iterator.hpp>
#include <mode/method/general_linear/explicit_general_linear_method.hpp>
#include <mode/method/general_linear/implicit_general_linear_method.hpp>
#include <mode/method/multi_stage/explicit_multi_stage_method.hpp>
#include <mode/method/multi_stage/implicit_multi_stage_method.hpp>
#include <mode/method/multi_step/explicit_multi_step_method.hpp>
#include <mode/method/multi_step/implicit_multi_step_method.hpp>
#include <mode/method/shooting_method_adapter.hpp>
#include <mode/problem/boundary_value_problem.hpp>
#include <mode/problem/initial_value_problem.hpp>
#include <mode/quantity/jacobian.hpp>
#include <mode/quantity/quantity_operations.hpp>
#include <mode/root_finder/newton_root_finder.hpp>
#include <mode/tableau/butcher/explicit/bogacki_shampine_5.hpp>
#include <mode/tableau/butcher/explicit/butcher_runge_kutta_6.hpp>
#include <mode/tableau/butcher/explicit/dormand_prince_5.hpp>
#include <mode/tableau/butcher/explicit/fehlberg_5.hpp>
#include <mode/tableau/butcher/explicit/forward_euler.hpp>
#include <mode/tableau/butcher/explicit/heun.hpp>
#include <mode/tableau/butcher/explicit/merson_4.hpp>
#include <mode/tableau/butcher/explicit/midpoint.hpp>
#include <mode/tableau/butcher/explicit/ralston.hpp>
#include <mode/tableau/butcher/explicit/runge_kutta_4.hpp>
#include <mode/tableau/butcher/explicit/tsitouras_5.hpp>
#include <mode/tableau/butcher/explicit/van_der_houwen_wray_3.hpp>
#include <mode/tableau/butcher/implicit/backward_euler.hpp>
#include <mode/tableau/butcher/implicit/crank_nicolson.hpp>
#include <mode/tableau/butcher/implicit/implicit_midpoint.hpp>
#include <mode/tableau/butcher/implicit/lobatto_IIIA.hpp>
#include <mode/tableau/butcher/implicit/lobatto_IIIB.hpp>
#include <mode/tableau/butcher/implicit/lobatto_IIIC.hpp>
#include <mode/tableau/butcher/implicit/lobatto_IIICs.hpp>
#include <mode/tableau/butcher/implicit/lobatto_IIID.hpp>
#include <mode/tableau/butcher/implicit/radau_IA.hpp>
#include <mode/tableau/butcher/implicit/radau_IIA.hpp>
#include <mode/tableau/butcher/implicit/rodas_4.hpp>
#include <mode/tableau/multi_step/adams_bashforth.hpp>
#include <mode/tableau/multi_step/backward_differentiation.hpp>
#include <mode/tableau/butcher_tableau.hpp>
#include <mode/tableau/general_linear_tableau.hpp>
#include <mode/tableau/multi_step_tableau.hpp>
#include <mode/utility/constexpr_for.hpp>
#include <mode/utility/parameter_pack_expander.hpp>
#include <mode/utility/sequence.hpp>
#include <mode/utility/static_assert_trigger.hpp>
#include <mode/utility/triangular_number.hpp>